[workspace]
members = [
    "crates/command_central",
    "crates/egui_command_palette",
    "crates/observable_key_value_tree",
    "crates/sdf_consts",
]
resolver = "2"

[workspace.dependencies]
command_central = { path = "crates/command_central" }
lazy_static = "1.5.0"
observable_key_value_tree = { path = "crates/observable_key_value_tree" }
sdf_consts = { path = "crates/sdf_consts" }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
uuid = { version = "1.26.1", features = ["serde", "v4", "js"] }
glam = { version = "0.32.1", features = ["serde"] }
egui_command_palette = { path = "crates/egui_command_palette" }

[package]
name    = "claydash"
version = "0.0.0"
edition = "2021"

[dependencies]
sdf_consts = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
command_central = { workspace = true }
uuid = { workspace = true }
observable_key_value_tree = { workspace = true }
glam = { workspace = true }
egui = "0.36.2"
egui_extras = { version = "0.36.2", default-features = false, features = ["svg"] }
egui_frames = { git = "https://github.com/antoineMoPa/egui_frames", rev = "ea7892f5081983f47322a132bee982ca88d95027", features = ["serde"] }
egui_command_palette = { workspace = true }
egui-wgpu = "0.36.2"
rfd = "0.17.2"
wgpu = "30.0.1"
winit = "0.30.13"
web-time = "1.1.0"
bytemuck = { version = "1.24.0", features = ["derive"] }
half = "2.7.1"
png = "0.17.16"
mp4 = "0.14.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pollster = "0.4.0"
openh264 = "0.9.8"
egui-winit = { version = "0.36.2", default-features = false }
base64 = "0.22"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.128"
wasm-bindgen-futures = "0.4.55"
console_error_panic_hook = "0.1.7"
js-sys = "0.3.105"

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3.105"
features = [
  'HtmlCanvasElement',
  'HtmlAnchorElement',
  'Blob',
  'BlobPropertyBag',
  'Document',
  'HtmlElement',
  'Node',
  'Storage',
  'Url',
  'Window',
]

[[bin]]
name = "claydash"
path = "./src/main.rs"

[profile.dev]
opt-level = 3
