[workspace]
members = [
    "crates/command_central",
    "crates/observable_key_value_tree",
    "crates/sdf_consts",
]
resolver = "2"

[workspace.dependencies]
command_central = { path = "crates/command_central" }
lazy_static = "1.5.0"
observable_key_value_tree = { path = "crates/observable_key_value_tree" }
sdf_consts = { path = "crates/sdf_consts" }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
uuid = { version = "1.26.1", features = ["serde", "v4"] }
glam = { version = "0.32.1", features = ["serde"] }

[package]
name    = "claydash"
version = "0.0.0"
edition = "2021"

[dependencies]
sdf_consts = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
command_central = { workspace = true }
uuid = { workspace = true }
observable_key_value_tree = { workspace = true }
rfd = "0.17.2"
lazy_static = { workspace = true }
glam = { workspace = true }
egui = "0.36.2"
egui-winit = "0.36.2"
egui-wgpu = "0.36.2"
wgpu = "30.0.1"
winit = "0.30.13"
pollster = "0.4.0"
bytemuck = { version = "1.24.0", features = ["derive"] }

[dependencies.web-sys]
version = "0.3.105"
features = [
  'Window',
]

[[bin]]
name = "main"
path = "./src/main.rs"

[profile.dev]
opt-level = 3
