[workspace]
members = [
    "crates/command_central",
    "crates/observable_key_value_tree",
    "crates/sdf_consts",
]
resolver = "2"

[workspace.dependencies]
bevy = "0.19.0"
bevy_egui = "0.42.0"
command_central = { path = "crates/command_central" }
lazy_static = "1.5.0"
observable_key_value_tree = { path = "crates/observable_key_value_tree" }
sdf_consts = { path = "crates/sdf_consts" }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
uuid = { version = "1.26.1", features = ["serde", "v4"] }

[package]
name    = "claydash"
version = "0.0.0"
edition = "2021"

[dependencies]
sdf_consts = { workspace = true }
bevy = { workspace = true, features = [ "serialize" ] }
serde = { workspace = true }
serde_json = { workspace = true }
bevy_egui = { workspace = true }
command_central = { workspace = true }
uuid = { workspace = true }
observable_key_value_tree = { workspace = true }
bevy_framepace = "0.22.0"
rfd = "0.17.2"
lazy_static = { workspace = true }

[dependencies.web-sys]
version = "0.3.105"
features = [
  'Window',
]

[[bin]]
name = "main"
path = "./src/main.rs"

[profile.dev]
opt-level = 3
