[package]
name = "claydash_engine"
version = "0.0.0"
edition = "2021"

[dependencies]
sdf_consts = { workspace = true }
screened_poisson = { path = "../screened_poisson" }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
glam = { workspace = true }
egui = "0.36.2"
egui-wgpu = "0.36.2"
wgpu = "30.0.1"
winit = "0.30.13"
web-time = "1.1.0"
bytemuck = { version = "1.24.0", features = ["derive"] }
half = "2.7.1"
png = "0.17.16"
image = { version = "0.25.10", default-features = false, features = ["png", "jpeg", "webp"] }
ttf-parser = "0.25.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pollster = "0.4.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.128"
wasm-bindgen-futures = "0.4.55"
js-sys = "0.3.105"
web-sys = { version = "0.3.105", features = ["Worker", "WorkerOptions", "WorkerType", "MessageEvent", "ErrorEvent"] }
