struct Camera { inverse_view_projection: mat4x4<f32>, position: vec4<f32>, count: vec4<u32> }
struct Object { state: vec4<i32>, color: vec4<f32>, inverse_rows: array<vec4<f32>, 3>, params: vec4<f32> }
struct BvhNode { center_radius: vec4<f32>, metadata: vec4<u32> }
@group(0) @binding(0) var<uniform> camera: Camera;
@group(0) @binding(1) var<storage, read> objects: array<Object>;
@group(0) @binding(2) var<storage, read> bvh: array<BvhNode>;
override USE_BVH: bool = true;

struct VertexOutput { @builtin(position) position: vec4<f32>, @location(0) clip: vec2<f32> }
@vertex fn vs_main(@builtin(vertex_index) index: u32) -> VertexOutput { var positions = array<vec2<f32>, 3>(vec2(-1.0, -3.0), vec2(3.0, 1.0), vec2(-1.0, 1.0)); var out: VertexOutput; out.clip = positions[index]; out.position = vec4(out.clip, 0.0, 1.0); return out; }
fn object_distance(point: vec3<f32>, object: Object) -> f32 { let homogeneous = vec4(point, 1.0); let local = vec3(dot(object.inverse_rows[0], homogeneous), dot(object.inverse_rows[1], homogeneous), dot(object.inverse_rows[2], homogeneous)); var distance = 100.0; if object.state.y == 1 { distance = length(local) - object.params.x; } else if object.state.y == 2 { let q = abs(local) - object.params.xyz; distance = length(max(q, vec3(0.0))) + min(max(q.x, max(q.y, q.z)), 0.0); } return distance * object.params.w; }
fn scene_distance(point: vec3<f32>) -> vec2<f32> { var closest = 100.0; var object_index = 0u; if USE_BVH { var node_index = 0u; while node_index < camera.count.y { let node = bvh[node_index]; let lower_bound = distance(point, node.center_radius.xyz) - node.center_radius.w; if lower_bound < closest { if node.metadata.x != 0xffffffffu { let candidate = object_distance(point, objects[node.metadata.x]); if candidate < closest { closest = candidate; object_index = node.metadata.x; } } node_index += 1u; } else { node_index = node.metadata.y; } } } else { for (var i = 0u; i < camera.count.x; i++) { let candidate = object_distance(point, objects[i]); if candidate < closest { closest = candidate; object_index = i; } } } return vec2(closest, f32(object_index)); }
fn object_normal(point: vec3<f32>, object: Object) -> vec3<f32> { let e = 0.003; let a = vec3(1.0, -1.0, -1.0); let b = vec3(-1.0, -1.0, 1.0); let c = vec3(-1.0, 1.0, -1.0); let d = vec3(1.0, 1.0, 1.0); return normalize(a * object_distance(point + a * e, object) + b * object_distance(point + b * e, object) + c * object_distance(point + c * e, object) + d * object_distance(point + d * e, object)); }
@fragment fn fs_main(input: VertexOutput) -> @location(0) vec4<f32> { let far = camera.inverse_view_projection * vec4(input.clip, 1.0, 1.0); let ray = normalize(far.xyz / far.w - camera.position.xyz); var travel = 0.0; var point = camera.position.xyz; var hit = false; var index = 0u; for (var step = 0; step < 64; step++) { let scene = scene_distance(point); if scene.x < 0.003 { hit = true; index = u32(scene.y); break; } travel += scene.x * 0.8; if travel > 100.0 { break; } point = camera.position.xyz + ray * travel; } if !hit { let horizon = max(ray.y, 0.0); return vec4(0.01 + horizon * 0.03, 0.01 + horizon * 0.03, 0.015 + horizon * 0.05, 1.0); } let object = objects[index]; let light = normalize(vec3(2.0, 3.0, 2.0) - point); let diffuse = max(dot(object_normal(point, object), light), 0.0); let selected = f32(object.state.x) * 0.2; return vec4(object.color.rgb * (0.3 + diffuse * 0.7) + selected, 1.0); }
