struct Camera { inverse_view_projection: mat4x4<f32>, position: vec4<f32>, count: vec4<u32> }
struct Object { state: vec4<i32>, color: vec4<f32>, inverse_transform: mat4x4<f32>, params: vec4<f32> }
@group(0) @binding(0) var<uniform> camera: Camera;
@group(0) @binding(1) var<storage, read> objects: array<Object>;

struct VertexOutput { @builtin(position) position: vec4<f32>, @location(0) clip: vec2<f32> }
@vertex fn vs_main(@builtin(vertex_index) index: u32) -> VertexOutput { var positions = array<vec2<f32>, 3>(vec2(-1.0, -3.0), vec2(3.0, 1.0), vec2(-1.0, 1.0)); var out: VertexOutput; out.clip = positions[index]; out.position = vec4(out.clip, 0.0, 1.0); return out; }
fn object_distance(point: vec3<f32>, object: Object) -> f32 { let local = (object.inverse_transform * vec4(point, 1.0)).xyz; var distance = 100.0; if object.state.y == 1 { distance = length(local) - object.params.x; } else if object.state.y == 2 { let q = abs(local) - object.params.xyz; distance = length(max(q, vec3(0.0))) + min(max(q.x, max(q.y, q.z)), 0.0); } let scale = vec3(length(object.inverse_transform[0].xyz), length(object.inverse_transform[1].xyz), length(object.inverse_transform[2].xyz)); return distance / max(length(scale), 0.001); }
fn scene_distance(point: vec3<f32>) -> vec2<f32> { var closest = 100.0; var index = 0.0; for (var i = 0u; i < camera.count.x; i++) { let distance = object_distance(point, objects[i]); if distance < closest { closest = distance; index = f32(i); } } return vec2(closest, index); }
fn normal(point: vec3<f32>) -> vec3<f32> { let e = 0.003; return normalize(vec3(scene_distance(point + vec3(e, 0.0, 0.0)).x - scene_distance(point - vec3(e, 0.0, 0.0)).x, scene_distance(point + vec3(0.0, e, 0.0)).x - scene_distance(point - vec3(0.0, e, 0.0)).x, scene_distance(point + vec3(0.0, 0.0, e)).x - scene_distance(point - vec3(0.0, 0.0, e)).x)); }
@fragment fn fs_main(input: VertexOutput) -> @location(0) vec4<f32> { let far = camera.inverse_view_projection * vec4(input.clip, 1.0, 1.0); let ray = normalize(far.xyz / far.w - camera.position.xyz); var point = camera.position.xyz; var hit = false; var index = 0u; for (var step = 0; step < 64; step++) { let scene = scene_distance(point); if scene.x < 0.003 { hit = true; index = u32(scene.y); break; } point += ray * scene.x * 0.8; if distance(point, camera.position.xyz) > 100.0 { break; } } if !hit { let horizon = max(ray.y, 0.0); return vec4(0.01 + horizon * 0.03, 0.01 + horizon * 0.03, 0.015 + horizon * 0.05, 1.0); } let object = objects[index]; let light = normalize(vec3(2.0, 3.0, 2.0) - point); let diffuse = max(dot(normal(point), light), 0.0); let selected = f32(object.state.x) * 0.2; return vec4(object.color.rgb * (0.3 + diffuse * 0.7) + selected, 1.0); }
