[package]
name = "claydash_scene_data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.3"
serde = "1.0.190"
serde_json = "1.0.108"
