[package]
name = "bevy_command_central_egui"
version = "0.1.0"
edition = "2021"

[dependencies]
command_central = { workspace = true }
bevy_command_central_plugin = { workspace = true }
bevy = { workspace = true }
bevy_egui = { workspace = true }
epaint = "0.23.0"
